# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LasBuildSeg
                                 A QGIS plugin
 An automated building footprint extraction pipeline and Python library from LiDAR point clouds.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-13
        copyright            : (C) 2026 by Mertcan Erdem/Berk Anbaroğlu
        email                : merterdemcan@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LasBuildSeg class from file LasBuildSeg.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .las_build_seg import LasBuildSeg
    return LasBuildSeg(iface)
