# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LasBuildSeg
                                 A QGIS plugin
 An automated building footprint extraction pipeline and Python library from LiDAR point clouds.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-06-13
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Mertcan Erdem/Berk Anbaroğlu
        email                : merterdemcan@hotmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
import sys
import subprocess
import json
import math
from qgis.PyQt.QtWidgets import QAction, QMessageBox, QProgressDialog
from qgis.PyQt.QtCore import QVariant, Qt
from qgis.core import (
    QgsProject, QgsVectorLayer, QgsFeature, QgsGeometry, 
    QgsField, QgsVectorFileWriter, QgsApplication, 
    QgsCoordinateReferenceSystem, QgsPointXY, QgsMessageLog, Qgis,
    QgsCoordinateTransformContext, QgsCoordinateTransform
)

# Add core directory to path for dependency management
plugin_dir = os.path.dirname(os.path.abspath(__file__))
core_dir = os.path.join(plugin_dir, 'core')
if core_dir not in sys.path:
    sys.path.insert(0, core_dir)

# Import dialog
try:
    from .LasBuildSeg_dialog import LasBuildSegDialog
except:
    from LasBuildSeg_dialog import LasBuildSegDialog


class LasBuildSeg:
    def __init__(self, iface):
        self.iface = iface
        self.dlg = LasBuildSegDialog()
        self._running = False  # re-entrancy guard
        if hasattr(self.dlg, 'pushButton_Run'):
            self.dlg.pushButton_Run.clicked.connect(self.run_logic)

    def initGui(self):
        self.action = QAction("Run LasBuildSeg", self.iface.mainWindow())
        self.action.triggered.connect(self.show_dialog)
        self.iface.addPluginToMenu('&LasBuildSeg', self.action)
        self.iface.addToolBarIcon(self.action)
        
        # Dependency installer action
        self.dep_action = QAction("Install Dependencies", self.iface.mainWindow())
        self.dep_action.triggered.connect(self.show_dependency_installer)
        self.iface.addPluginToMenu('&LasBuildSeg', self.dep_action)

    def unload(self):
        self.iface.removePluginMenu('&LasBuildSeg', self.action)
        self.iface.removeToolBarIcon(self.action)
        self.iface.removePluginMenu('&LasBuildSeg', self.dep_action)

    def show_dependency_installer(self):
        """Show dependency installation dialog"""
        try:
            ui_dir = os.path.join(plugin_dir, 'ui')
            if ui_dir not in sys.path:
                sys.path.insert(0, ui_dir)
            
            from dependency_installer_dialog import DependencyInstallerDialog
            dlg = DependencyInstallerDialog(self.iface.mainWindow())
            dlg.exec_()
        except Exception as e:
            import traceback
            QMessageBox.critical(
                self.iface.mainWindow(),
                "Error",
                f"Failed to open dependency installer:\n{str(e)}\n\n{traceback.format_exc()}"
            )

    def check_dependencies(self) -> bool:
        """Check if dependencies are installed before running"""
        try:
            # Make sure core directory is in path
            if core_dir not in sys.path:
                sys.path.insert(0, core_dir)
            
            from venv_manager import get_venv_status, ensure_venv_packages_available
            
            is_ready, status_msg = get_venv_status()
            
            if not is_ready:
                reply = QMessageBox.warning(
                    self.iface.mainWindow(),
                    "Dependencies Not Installed",
                    f"LasBuildSeg requires Python libraries:\n"
                    f"• numpy (array operations)\n"
                    f"• scipy (interpolation, morphology)\n"
                    f"• alphashape (boundary extraction)\n"
                    f"• CSF (ground filtering)\n\n"
                    f"GDAL comes with QGIS (no install needed)\n\n"
                    f"Status: {status_msg}\n\n"
                    f"Install now? (~80 MB, 1-2 minutes)",
                    QMessageBox.Yes | QMessageBox.No
                )
                
                if reply == QMessageBox.Yes:
                    self.show_dependency_installer()
                
                return False
            
            # Ensure packages are available in sys.path
            ensure_venv_packages_available()
            return True
            
        except Exception as e:
            import traceback
            error_trace = traceback.format_exc()
            QgsMessageLog.logMessage(f"Dependency check error:\n{error_trace}", "LasBuildSeg", level=Qgis.Critical)
            
            QMessageBox.critical(
                self.iface.mainWindow(),
                "Dependency Check Failed",
                f"Failed to check dependencies:\n{str(e)}\n\n"
                f"Try: Plugins → LasBuildSeg → Install Dependencies\n\n"
                f"Details logged to QGIS message log."
            )
            return False

    def show_dialog(self):
        # Check dependencies before showing dialog
        if not self.check_dependencies():
            return
        self.dlg.show()

    # =========================================================================
    # 1. PDAL UTILS
    # =========================================================================
    def get_pdal_exe(self):
        pdal_exe = r"C:\Program Files\QGIS 3.44.1\bin\pdal.exe"
        if os.path.exists(pdal_exe): return pdal_exe
        pdal_exe = os.path.join(QgsApplication.prefixPath(), "bin", "pdal.exe")
        if os.path.exists(pdal_exe): return pdal_exe
        try:
            subprocess.run(["pdal", "--version"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            return "pdal"
        except:
            pass
        raise Exception("PDAL executable not found.")

    def run_pdal_pipeline(self, pipeline_json):
        pdal_exe = self.get_pdal_exe()
        env = os.environ.copy()
        qgis_root = QgsApplication.prefixPath()
        proj_candidates = [
            os.path.join(qgis_root, "share", "proj"),
            os.path.join(qgis_root, "..", "share", "proj")
        ]
        for p in proj_candidates:
            if os.path.exists(os.path.join(p, "proj.db")):
                env["PROJ_LIB"] = p
                break
        
        cmd = [pdal_exe, "pipeline", "--stdin"]
        
        startupinfo = None
        if sys.platform == "win32":
            startupinfo = subprocess.STARTUPINFO()
            startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
            startupinfo.wShowWindow = subprocess.SW_HIDE
        
        # Log the pipeline for debugging
        try:
            pipeline_dict = json.loads(pipeline_json)
            QgsMessageLog.logMessage(f"PDAL Pipeline: {json.dumps(pipeline_dict, indent=2)}", "LasBuildSeg", level=Qgis.Info)
        except:
            pass
        
        process = subprocess.run(
            cmd, 
            input=pipeline_json.encode('utf-8'), 
            env=env, 
            stdout=subprocess.PIPE, 
            stderr=subprocess.PIPE, 
            startupinfo=startupinfo,
            cwd=os.getcwd()
        )
        
        if process.returncode != 0:
            error_msg = process.stderr.decode()
            if "Permission denied" in error_msg:
                raise Exception(
                    f"PDAL Permission Error:\n{error_msg}\n\n"
                    f"Try:\n"
                    f"1. Select a different output folder with write permissions\n"
                    f"2. Run QGIS as administrator\n"
                    f"3. Check if output files are open in another program"
                )
            else:
                raise Exception(f"PDAL Error: {error_msg}")
        
        return process.stdout.decode()

    def save_raster_qgis(self, data, path, transform, proj_wkt, nodata=-9999):
        from osgeo import gdal
        
        driver = gdal.GetDriverByName('GTiff')
        rows, cols = data.shape
        ds = driver.Create(path, cols, rows, 1, gdal.GDT_Float32)
        ds.SetGeoTransform(transform)
        ds.SetProjection(proj_wkt)
        ds.GetRasterBand(1).WriteArray(data)
        ds.GetRasterBand(1).SetNoDataValue(nodata)
        ds.FlushCache()
        ds = None

    # =========================================================================
    # NEW: LAZ PRE-ANALYSIS FUNCTION
    # =========================================================================
    def laz_pre_analysis(self, laz_path):
        """Port of standalone laz_pre_analysis — uses all-return count + all-return slope."""
        import numpy as np
        pdal_exe = self.get_pdal_exe()
        env = os.environ.copy()
        si = None
        if sys.platform == 'win32':
            si = subprocess.STARTUPINFO()
            si.dwFlags |= subprocess.STARTF_USESHOWWINDOW
            si.wShowWindow = subprocess.SW_HIDE
        r = subprocess.run([pdal_exe, 'info', '--metadata', laz_path],
            capture_output=True, text=True, timeout=120, env=env, startupinfo=si)
        meta = json.loads(r.stdout).get('metadata', {})
        total = int(meta.get('count', 0))
        area  = (float(meta.get('maxx',0)) - float(meta.get('minx',0))) * \
                (float(meta.get('maxy',0)) - float(meta.get('miny',0)))
        point_density = total / area if area > 0 else 10.0

        # All-returns decimated sample for slope (no filters.returns — matches las.x/y/z)
        step = max(1, total // 500_000)
        tmp = laz_path.replace('.laz','_ana.txt').replace('.las','_ana.txt')
        self.run_pdal_pipeline(json.dumps({'pipeline': [laz_path,
            {'type':'filters.decimation','step':step},
            {'type':'writers.text','filename':tmp,'order':'X,Y,Z',
             'keep_unspecified':'false','delimiter':',','write_header':False}]}))
        pts = np.loadtxt(tmp, delimiter=',', dtype=np.float32)
        if os.path.exists(tmp): os.remove(tmp)

        c,_,_,_ = np.linalg.lstsq(
            np.column_stack((pts[:,0], pts[:,1], np.ones(len(pts)))), pts[:,2], rcond=None)
        slope = math.sqrt(c[0]**2 + c[1]**2)
        cloth_res = 0.5 if point_density>15 else (1.0 if point_density>5 else 2.0)
        rigidness = 1 if slope>0.3 else (2 if slope>0.1 else 3)
        self.iface.messageBar().pushMessage('LasBuildSeg',
            f'density={point_density:.2f} slope={slope:.4f} → CSF res={cloth_res} rigid={rigidness}',
            level=Qgis.Info)
        return {'cloth_resolution': cloth_res, 'rigidness': rigidness, 'class_threshold': 0.1}

    # =========================================================================
    # 2. GENERATION (DSM / DTM) - USING LAST RETURNS
    # =========================================================================
    def generate_dsm_pdal(self, laz_path, out_path, resolution=1.0):
        """
        Port of standalone generate_dsm_last_returns.
        griddata(nearest), void masking, bottom-up orientation (positive Y step),
        CRS read from PDAL output (VLR binary records), returns detected EPSG.
        """
        import numpy as np, scipy.interpolate
        from osgeo import gdal, osr
        from scipy.ndimage import maximum_filter

        tmp = laz_path.replace('.laz','_dsm.txt').replace('.las','_dsm.txt')
        self.run_pdal_pipeline(json.dumps({'pipeline': [laz_path,
            {'type':'filters.returns','groups':'last,only'},
            {'type':'writers.text','filename':tmp,'order':'X,Y,Z',
             'keep_unspecified':'false','delimiter':',','write_header':False}]}))
        pts = np.loadtxt(tmp, delimiter=',', dtype=np.float64)
        if os.path.exists(tmp): os.remove(tmp)

        x, y, z = pts[:,0], pts[:,1], pts[:,2]
        x_min = float(np.floor(x.min())); x_max = float(np.ceil(x.max()))
        y_min = float(np.floor(y.min())); y_max = float(np.ceil(y.max()))

        # Exactly matches standalone: arange(x_min,x_max,res) × arange(y_min,y_max,res)
        # row 0 = southernmost (Affine(res,0,x_min,0,res,y_min) convention)
        gx, gy = np.meshgrid(np.arange(x_min, x_max, resolution),
                              np.arange(y_min, y_max, resolution))
        nr, nc = gx.shape
        dsm = scipy.interpolate.griddata((x,y), z, (gx,gy), method='nearest').astype(np.float32)

        # Void masking — same as standalone maximum_filter approach
        ci = np.clip(((x-x_min)/resolution).astype(int), 0, nc-1)
        ri = np.clip(((y-y_min)/resolution).astype(int), 0, nr-1)
        cnt = np.zeros((nr,nc), dtype=np.int32)
        np.add.at(cnt, (ri,ci), 1)
        dsm[~maximum_filter(cnt>0, size=3)] = np.float32(-9999)
        dsm = np.where(np.isnan(dsm), np.float32(-9999), dsm)

        # Bottom-up geotransform — positive Y step, row 0 = south
        gt = (x_min, resolution, 0.0, y_min, 0.0, resolution)
        self._dsm_gt = gt; self._dsm_shape = (nr, nc)

        # CRS from PDAL (reads binary VLR records that pdal info --metadata often misses)
        proj_wkt = ''
        try:
            ctmp = out_path + '_crs.tif'
            self.run_pdal_pipeline(json.dumps({'pipeline': [laz_path,
                {'type':'filters.head','count':1},
                {'type':'writers.gdal','filename':ctmp,'resolution':resolution,
                 'output_type':'max','data_type':'float','nodata':-9999}]}))
            _ds = gdal.Open(ctmp)
            if _ds: proj_wkt = _ds.GetProjection() or ''; _ds = None
            if os.path.exists(ctmp): os.remove(ctmp)
        except Exception as e:
            QgsMessageLog.logMessage(f'CRS probe: {e}','LasBuildSeg',level=Qgis.Warning)
        self._dsm_proj_wkt = proj_wkt

        drv = gdal.GetDriverByName('GTiff')
        ds = drv.Create(out_path, nc, nr, 1, gdal.GDT_Float32)
        ds.SetGeoTransform(gt)
        if proj_wkt: ds.SetProjection(proj_wkt)
        bnd = ds.GetRasterBand(1); bnd.SetNoDataValue(-9999); bnd.WriteArray(dsm)
        ds.FlushCache(); ds = None

        epsg = 0
        if proj_wkt:
            try:
                s = osr.SpatialReference(); s.ImportFromWkt(proj_wkt)
                c = s.GetAuthorityCode(None)
                if c and str(c).isdigit(): epsg = int(c)
            except Exception: pass
        if epsg:
            self.iface.messageBar().pushMessage('LasBuildSeg',f'CRS: EPSG:{epsg}',level=Qgis.Info)
        return epsg

    def generate_dtm_csf_pdal(self, laz_path, reference_dsm_path, csf_params):
        """
        Port of standalone generate_dtm_with_csf_last_returns.
        Uses linspace grid matching DSM bounds (same as standalone).
        Same bottom-up orientation as DSM — no alignment needed.
        """
        import numpy as np, scipy.interpolate, CSF
        from osgeo import gdal

        gt = getattr(self,'_dsm_gt',None); shape = getattr(self,'_dsm_shape',None)
        proj_wkt = getattr(self,'_dsm_proj_wkt','')
        if gt is None:
            _ds = gdal.Open(reference_dsm_path)
            gt = _ds.GetGeoTransform(); shape = (_ds.RasterYSize, _ds.RasterXSize)
            proj_wkt = _ds.GetProjection(); _ds = None

        nr, nc = shape; x0, rx, _, y0, _, ry = gt  # ry > 0 (south-up)

        # Exact port: x=linspace(bounds.left,bounds.right,width), y=linspace(bounds.bottom,bounds.top,height)
        # bounds.left=x0, bounds.right=x0+nc*rx, bounds.bottom=y0, bounds.top=y0+nr*ry
        gx, gy = np.meshgrid(np.linspace(x0, x0+nc*rx, nc),
                              np.linspace(y0, y0+nr*ry, nr))   # row 0 = south

        tmp = laz_path.replace('.laz','_dtm.txt').replace('.las','_dtm.txt')
        self.run_pdal_pipeline(json.dumps({'pipeline': [laz_path,
            {'type':'filters.returns','groups':'last,only'},
            {'type':'writers.text','filename':tmp,'order':'X,Y,Z',
             'keep_unspecified':'false','delimiter':',','write_header':False}]}))
        pts = np.loadtxt(tmp, delimiter=',', dtype=np.float64)
        if os.path.exists(tmp): os.remove(tmp)

        csf = CSF.CSF(); csf.params.bSloopSmooth = True
        csf.params.cloth_resolution = csf_params.get('cloth_resolution', 1.0)
        csf.params.rigidness        = csf_params.get('rigidness', 3)
        csf.params.class_threshold  = csf_params.get('class_threshold', 0.1)
        csf.setPointCloud(pts)
        gi = CSF.VecInt(); ngi = CSF.VecInt(); csf.do_filtering(gi, ngi)
        gp = pts[list(gi)]

        dtm = scipy.interpolate.griddata(
            (gp[:,0],gp[:,1]), gp[:,2], (gx,gy), method='nearest').astype(np.float32)
        return dtm, gt, proj_wkt

    # =========================================================================
    # 3. ANALYSIS & FILTERING
    # =========================================================================
    def calculate_global_tri(self, dsm_array, resolution=1.0):
        """Calculate Terrain Ruggedness Index (gradient magnitude)."""
        import numpy as np
        dy, dx = np.gradient(dsm_array)
        tri = np.sqrt(dx**2 + dy**2)
        tri /= resolution
        return tri

    def analyze_low_res_ndhm(self, ndhm_array, downscale_factor=3, ndhm_path=None):
        """
        Port of standalone analyze_low_res_ndhm.
        Uses GDAL ReadAsArray(buf_xsize, buf_ysize) for downsampling, which
        matches rasterio Resampling.average (GDAL average resampling under the hood).
        This is critical: numpy reshape+mean gives different statistics near void
        areas compared to rasterio's average resampling.
        """
        import numpy as np
        from osgeo import gdal

        self.iface.messageBar().pushMessage('LasBuildSeg',
            f'Analysing coarse-scale nDSM (downscale 1/{downscale_factor})…', level=Qgis.Info)

        if ndhm_path and os.path.exists(ndhm_path):
            # Read from disk using GDAL average resampling — matches rasterio Resampling.average
            ds = gdal.Open(ndhm_path)
            bnd = ds.GetRasterBand(1)
            full_w, full_h = ds.RasterXSize, ds.RasterYSize
            new_w = full_w // downscale_factor
            new_h = full_h // downscale_factor
            # GDAL ReadAsArray with buf_xsize/buf_ysize does average downsampling
            low_res_data = bnd.ReadAsArray(0, 0, full_w, full_h,
                                           buf_xsize=new_w, buf_ysize=new_h,
                                           resample_alg=gdal.GRIORA_Average)
            ds = None
        else:
            # Fallback: numpy average (less accurate near voids)
            h, w = ndhm_array.shape
            new_h = h // downscale_factor; new_w = w // downscale_factor
            arr = ndhm_array[:new_h*downscale_factor, :new_w*downscale_factor]
            low_res_data = arr.reshape(new_h, downscale_factor, new_w, downscale_factor).mean(axis=(1,3))

        potential_buildings = low_res_data[low_res_data > 2.5]
        avg_height = np.mean(potential_buildings) if potential_buildings.size > 0 else 5.0

        gy, gx = np.gradient(low_res_data)
        slope = np.sqrt(gx**2 + gy**2)
        potential_slopes = slope[low_res_data > 2.5]
        avg_slope = np.percentile(potential_slopes, 85) if potential_slopes.size > 0 else 1.0

        alphashape_height_thresh = avg_height * 0.4
        if alphashape_height_thresh < 2.0: alphashape_height_thresh = 2.0
        filter_height_thresh = alphashape_height_thresh * 0.8
        adaptive_tri_thresh = avg_slope * 0.75
        if adaptive_tri_thresh < 1.0: adaptive_tri_thresh = 1.0

        self.iface.messageBar().pushMessage('Adaptive Thresholds',
            f'AlphaShape Height={alphashape_height_thresh:.2f}, '
            f'Filter Height={filter_height_thresh:.2f} (80%), TRI={adaptive_tri_thresh:.2f}',
            level=Qgis.Info)
        return alphashape_height_thresh, filter_height_thresh, adaptive_tri_thresh

    def get_geometry_stats(self, geom):
        """Calculate area, squareness, and width"""
        import numpy as np
        
        area = geom.area()
        if area == 0: return 0, 0, 0
        
        ombb_res = geom.orientedMinimumBoundingBox()
        ombb = ombb_res[0] if isinstance(ombb_res, tuple) else ombb_res
        
        poly = ombb.asPolygon()
        if not poly: return area, 0, 0
        ring = poly[0]
        
        d1 = np.sqrt((ring[0].x()-ring[1].x())**2 + (ring[0].y()-ring[1].y())**2)
        d2 = np.sqrt((ring[1].x()-ring[2].x())**2 + (ring[1].y()-ring[2].y())**2)
        
        width = min(d1, d2)
        bbox_area = d1 * d2
        sq = area / bbox_area if bbox_area > 0 else 0
        
        return area, sq, width

    def calculate_exact_masked_tri(self, geom, tri_map, ndhm_map, gt, filter_h_thresh):
        import numpy as np
        try:
            bbox=geom.boundingBox(); x0,rx,y0,ry=gt[0],gt[1],gt[3],gt[5]
            c0=max(0,int((bbox.xMinimum()-x0)/rx)); c1=min(tri_map.shape[1],int((bbox.xMaximum()-x0)/rx)+1)
            r0=max(0,int((bbox.yMinimum()-y0)/ry)); r1=min(tri_map.shape[0],int((bbox.yMaximum()-y0)/ry)+1)
            if r0>=r1 or c0>=c1: return 0.0
            s=0.0; n=0
            for r in range(r0,r1):
                for c in range(c0,c1):
                    if ndhm_map[r,c]>filter_h_thresh:
                        if geom.contains(QgsPointXY(x0+(c+0.5)*rx, y0+(r+0.5)*ry)):
                            v=tri_map[r,c]
                            if not np.isnan(v): s+=v; n+=1
            return s/n if n>0 else 0.0
        except: return 0.0

    # =========================================================================
    # NEW: PER-COMPONENT ALPHA SHAPE EXTRACTION
    # =========================================================================
    def extract_components_alpha(self, mask, gt, alpha):
        """
        NEW: Instead of one global alpha shape (which merges everything),
        label connected components first, then run alpha shape per component.
        This prevents vegetation patches from merging with buildings and
        gives much cleaner per-building polygons.
        """
        import numpy as np
        import alphashape
        from scipy.ndimage import label

        labeled, num_features = label(mask)
        geoms = []

        self.iface.messageBar().pushMessage(
            "LasBuildSeg",
            f"Found {num_features} raw connected components — running per-component alpha shape...",
            level=Qgis.Info
        )

        for comp_id in range(1, num_features + 1):
            comp_mask = labeled == comp_id
            rows, cols = np.where(comp_mask)

            if len(rows) < 4:
                continue  # too small to form a shape

            pts_x = gt[0] + (cols + 0.5) * gt[1]
            pts_y = gt[3] + (rows + 0.5) * gt[5]   # gt[5]>0, y increases northward
            pts = np.column_stack((pts_x, pts_y))

            try:
                shape = alphashape.alphashape(pts, alpha)
                if shape is None or shape.is_empty:
                    shape = alphashape.alphashape(pts, 0.0)

                if shape is None or shape.is_empty:
                    continue

                if shape.geom_type == 'Polygon':
                    geoms.append(shape)
                elif shape.geom_type == 'MultiPolygon':
                    geoms.extend(list(shape.geoms))
            except Exception:
                continue  # skip bad components silently

        return geoms

    # =========================================================================
    # NEW: ADVANCED FALSE-POSITIVE FILTERS
    # =========================================================================
    def calculate_height_variance(self, geom, ndhm, gt, filter_h_thresh):
        import numpy as np
        try:
            bbox=geom.boundingBox(); x0,rx,y0,ry=gt[0],gt[1],gt[3],gt[5]
            c0=max(0,int((bbox.xMinimum()-x0)/rx)); c1=min(ndhm.shape[1],int((bbox.xMaximum()-x0)/rx)+1)
            r0=max(0,int((bbox.yMinimum()-y0)/ry)); r1=min(ndhm.shape[0],int((bbox.yMaximum()-y0)/ry)+1)
            if r0>=r1 or c0>=c1: return 0.0
            h=[]
            for r in range(r0,r1):
                for c in range(c0,c1):
                    if ndhm[r,c]>filter_h_thresh:
                        if geom.contains(QgsPointXY(x0+(c+0.5)*rx, y0+(r+0.5)*ry)):
                            h.append(ndhm[r,c])
            return float(np.std(h)) if len(h)>=3 else 0.0
        except: return 0.0

    def calculate_convex_hull_ratio(self, geom):
        """
        NEW: Convex hull ratio = polygon area / convex hull area.
        Buildings are convex-ish (ratio near 1.0). Trees and irregular
        vegetation blobs are often concave and branchy (lower ratio).
        A very low ratio (e.g. < 0.5) usually indicates non-building.
        """
        try:
            hull = geom.convexHull()
            hull_area = hull.area()
            if hull_area == 0:
                return 0.0
            return geom.area() / hull_area
        except Exception:
            return 0.0

    def calculate_elongation(self, geom):
        """
        NEW: Elongation = max_side / min_side from the oriented bounding box.
        Very elongated shapes (ratio >> 1) are roads, power lines, walls —
        not buildings. Buildings typically have elongation < 5–6.
        """
        try:
            ombb_res = geom.orientedMinimumBoundingBox()
            ombb = ombb_res[0] if isinstance(ombb_res, tuple) else ombb_res
            poly = ombb.asPolygon()
            if not poly:
                return 1.0
            ring = poly[0]
            import numpy as np
            d1 = math.sqrt((ring[0].x() - ring[1].x())**2 + (ring[0].y() - ring[1].y())**2)
            d2 = math.sqrt((ring[1].x() - ring[2].x())**2 + (ring[1].y() - ring[2].y())**2)
            if min(d1, d2) == 0:
                return 1.0
            return max(d1, d2) / min(d1, d2)
        except Exception:
            return 1.0

    def extract_and_filter(self, ndhm, dsm, gt, crs_wkt, alpha, alphashape_h_thresh,
                           filter_h_thresh, tri_thresh, min_size, max_size, sq_thresh,
                           w_thresh, kernel_size, out_path,
                           height_var_thresh=2.5,
                           convex_hull_ratio_min=0.5,
                           max_elongation=8.0,
                           use_per_component=True,
                           epsg_code=None):
        """
        Extract and filter buildings with TWO-STAGE thresholds + advanced
        false-positive elimination.

        alphashape_h_thresh : 100% height threshold — used for initial mask.
        filter_h_thresh     : 80% height threshold — used for TRI + variance calc.

        NEW FILTERS (all optional — set to 0/999 to disable):
        height_var_thresh   : Max allowed height std-dev inside polygon.
                              Buildings = flat roofs (low). Trees = high. Default 2.5m.
                              Set 0 to disable.
        convex_hull_ratio_min : Min ratio polygon_area / convex_hull_area.
                              Very branchy/concave shapes dropped. Default 0.5.
                              Set 0 to disable.
        max_elongation      : Maximum length/width ratio from OBB.
                              Drop power lines / walls. Default 8.0.
                              Set 999 to disable.
        use_per_component   : If True, run alpha shape per connected component
                              instead of one global shape. Default True.
        """
        import numpy as np
        import alphashape
        from scipy.ndimage import binary_opening

        # ---- 1. INITIAL MASK (alphashape threshold) ----
        mask_raw = ndhm > alphashape_h_thresh

        # ---- 2. MORPHOLOGICAL OPENING (pre-alpha noise removal) ----
        if kernel_size > 0:
            self.iface.messageBar().pushMessage(
                "LasBuildSeg",
                f"Pre-Alpha Morphological Opening (kernel={kernel_size})...",
                level=Qgis.Info
            )
            structure = np.ones((kernel_size, kernel_size))
            mask = binary_opening(mask_raw, structure=structure)
            removed = int(np.sum(mask_raw)) - int(np.sum(mask))
            self.iface.messageBar().pushMessage(
                "Noise Removal",
                f"Removed {removed} noisy pixels via morphological opening",
                level=Qgis.Info
            )

            # ---- FXAA-style edge-smoothing (matches standalone adaptiveparams.py) ----
            # Replicates cv2.Sobel + cv2.GaussianBlur using scipy so no new libraries needed.
            from scipy.ndimage import sobel as _sobel, gaussian_filter as _gblur
            _img = mask.astype(np.float32)
            _gx = _sobel(_img, axis=1)
            _gy = _sobel(_img, axis=0)
            _edge = np.sqrt(_gx ** 2 + _gy ** 2)
            _edge /= (_edge.max() + 1e-6)
            _blurred = _gblur(_img, sigma=1.0)          # sigma≈1 ≈ GaussianBlur(3,3,0)
            _blend = 0.8                                 # same blend_strength as standalone
            _result = _img * (1 - _blend * _edge) + _blurred * (_blend * _edge)
            mask = (_result > 0.5).astype(np.uint8)
            self.iface.messageBar().pushMessage(
                "LasBuildSeg", "Applied FXAA-style edge smoothing to mask", level=Qgis.Info
            )
        else:
            mask = mask_raw

        rows, cols = np.where(mask)
        if len(rows) < 4:
            self.iface.messageBar().pushMessage(
                "Warning", "No pixels found after morphological opening.", level=Qgis.Warning
            )
            return

        # ---- 3. ALPHA SHAPE EXTRACTION ----
        if use_per_component:
            # NEW: Per-connected-component approach — much fewer merged blobs
            geoms = self.extract_components_alpha(mask, gt, alpha)
        else:
            # Legacy: single global alpha shape
            pts_x = gt[0] + (cols + 0.5) * gt[1]
            pts_y = gt[3] + (rows + 0.5) * gt[5]
            pts = np.unique(np.column_stack((pts_x, pts_y)), axis=0)
            try:
                self.iface.messageBar().pushMessage(
                    "LasBuildSeg", f"Generating global Alpha Shape (alpha={alpha})...", level=Qgis.Info
                )
                shape = alphashape.alphashape(pts, alpha)
                if shape.is_empty:
                    shape = alphashape.alphashape(pts, 0.2)
                if shape.is_empty:
                    shape = alphashape.alphashape(pts, 0.0)
            except Exception as e:
                self.iface.messageBar().pushMessage("Error", f"AlphaShape failed: {e}", level=Qgis.Critical)
                return
            geoms = []
            if shape.geom_type == 'Polygon':
                geoms.append(shape)
            elif shape.geom_type == 'MultiPolygon':
                geoms.extend(list(shape.geoms))

        # ---- 4. REPROJECTION ─ GDAL OSR OAMS_TRADITIONAL_GIS_ORDER ----
        from osgeo import ogr as _ogr, osr as _osr
        _out_epsg = 0
        if epsg_code and int(epsg_code) > 0:
            try:
                _s=_osr.SpatialReference(); _s.ImportFromEPSG(int(epsg_code))
                _s.SetAxisMappingStrategy(_osr.OAMS_TRADITIONAL_GIS_ORDER)
                _d=_osr.SpatialReference(); _d.ImportFromEPSG(3857)
                _d.SetAxisMappingStrategy(_osr.OAMS_TRADITIONAL_GIS_ORDER)
                _ct=_osr.CoordinateTransformation(_s,_d); _out_epsg=3857
                def _reproject_geom(sg):
                    og=_ogr.CreateGeometryFromWkt(sg.wkt); og.Transform(_ct)
                    return QgsGeometry.fromWkt(og.ExportToWkt())
                self.iface.messageBar().pushMessage('LasBuildSeg',
                    f'Reprojecting EPSG:{epsg_code} → EPSG:3857', level=Qgis.Info)
            except Exception as ex:
                QgsMessageLog.logMessage(f'Reproject:{ex}','LasBuildSeg',level=Qgis.Warning)
                epsg_code=0
        if not epsg_code or int(epsg_code)<=0:
            _out_epsg=0
            def _reproject_geom(sg): return QgsGeometry.fromWkt(sg.wkt)
            self.iface.messageBar().pushMessage('LasBuildSeg',
                'No EPSG — output in source coords. Set Input CRS in dialog.',level=Qgis.Warning)
        _crs_str = f'crs=EPSG:{_out_epsg}' if _out_epsg else 'crs='

        def _remove_layer_if_open(path):
            """
            Remove any QGIS layer currently pointing to this file path.
            Without this, writing to a file that's open as a QGIS layer either
            fails silently (Windows file lock) or writes but QGIS keeps showing
            the old cached version — making it look like parameters have no effect.
            """
            path_norm = os.path.normcase(os.path.abspath(path))
            to_remove = []
            for layer_id, layer in QgsProject.instance().mapLayers().items():
                try:
                    src = os.path.normcase(os.path.abspath(layer.source().split("|")[0]))
                    if src == path_norm:
                        to_remove.append(layer_id)
                except Exception:
                    pass
            if to_remove:
                QgsProject.instance().removeMapLayers(to_remove)

        def _write_geojson(layer, path):
            _remove_layer_if_open(path)
            opts = QgsVectorFileWriter.SaveVectorOptions()
            opts.driverName = "GeoJSON"
            opts.fileEncoding = "UTF-8"
            QgsVectorFileWriter.writeAsVectorFormatV2(
                layer, path, QgsCoordinateTransformContext(), opts
            )

        # ---- 5. SAVE DEBUG CANDIDATES (in 3857) ----
        debug_path = out_path.replace(".geojson", "_debug_candidates.geojson")
        debug_layer = QgsVectorLayer(f"Polygon?{_crs_str}", "Debug", "memory")
        dpr = debug_layer.dataProvider()
        dfeat = QgsFeature()
        for g in geoms:
            dfeat.setGeometry(_reproject_geom(g))
            dpr.addFeatures([dfeat])
        _write_geojson(debug_layer, debug_path)
        QgsProject.instance().addMapLayer(QgsVectorLayer(debug_path, "Debug Candidates", "ogr"))

        # ---- 6. GLOBAL TRI MAP ----
        tri_map = self.calculate_global_tri(dsm, abs(gt[1]))

        # ---- 7. MULTI-FILTER PASS ----
        # Note: geometry stats (area, width, squareness) are computed in the
        # SOURCE CRS before reprojection so pixel-space measurements stay accurate.
        # The geometry added to the output layer is the reprojected 3857 version.
        layer = QgsVectorLayer(f"Polygon?{_crs_str}", "Buildings", "memory")
        pr = layer.dataProvider()
        pr.addAttributes([
            QgsField("Area",           QVariant.Double),
            QgsField("Squareness",     QVariant.Double),
            QgsField("Width",          QVariant.Double),
            QgsField("TRI",            QVariant.Double),
            QgsField("HeightVar",      QVariant.Double),
            QgsField("ConvexRatio",    QVariant.Double),
            QgsField("Elongation",     QVariant.Double),
        ])
        layer.updateFields()

        valid_features = []
        dropped = {
            'area': 0, 'sq': 0, 'tri': 0, 'width': 0,
            'height_var': 0, 'convex': 0, 'elongation': 0
        }

        for g in geoms:
            # Stats computed in native (source) CRS — accurate pixel measurements
            qgs_geom_src = QgsGeometry.fromWkt(g.wkt)

            # Size/shape stats computed on 3857 geometry (sq meters, meters).
            # Standalone filter_contours operates on the 3857-rasterized image,
            # so min_size=50 means 50 sq meters not 50 sq feet.
            # Without this, min_size is in sq feet (10x too permissive for US Survey Feet data).
            if _out_epsg == 3857:
                qgs_geom_metric = _reproject_geom(g)
            else:
                qgs_geom_metric = qgs_geom_src   # fallback if no reprojection

            area, sq, width = self.get_geometry_stats(qgs_geom_metric)

            if not (min_size <= area <= max_size):
                dropped['area'] += 1
                continue
            if sq < sq_thresh:
                dropped['sq'] += 1
                continue
            if width < w_thresh:
                dropped['width'] += 1
                continue

            elongation = self.calculate_elongation(qgs_geom_src)
            if elongation > max_elongation:
                dropped['elongation'] += 1
                continue

            cvx_ratio = self.calculate_convex_hull_ratio(qgs_geom_src)
            if cvx_ratio < convex_hull_ratio_min:
                dropped['convex'] += 1
                continue

            tri_val = self.calculate_exact_masked_tri(qgs_geom_src, tri_map, ndhm, gt, filter_h_thresh)
            if tri_val > tri_thresh:
                dropped['tri'] += 1
                continue

            h_var = self.calculate_height_variance(qgs_geom_src, ndhm, gt, filter_h_thresh)
            if height_var_thresh > 0 and h_var > height_var_thresh:
                dropped['height_var'] += 1
                continue

            # Passed all filters — reproject to 3857 for output
            feat = QgsFeature()
            feat.setGeometry(_reproject_geom(g))
            feat.setAttributes([area, sq, width, tri_val, h_var, cvx_ratio, elongation])
            valid_features.append(feat)

        self.iface.messageBar().pushMessage(
            "Filtering Stats",
            (f"Kept={len(valid_features)} | Dropped: "
             f"Area={dropped['area']}, Sq={dropped['sq']}, Width={dropped['width']}, "
             f"TRI={dropped['tri']}, HeightVar={dropped['height_var']}, "
             f"Convex={dropped['convex']}, Elong={dropped['elongation']}"),
            level=Qgis.Info
        )

        if valid_features:
            pr.addFeatures(valid_features)
            layer.updateExtents()
            _write_geojson(layer, out_path)
            QgsProject.instance().addMapLayer(QgsVectorLayer(out_path, "Filtered Buildings", "ogr"))
            self.iface.messageBar().pushMessage(
                "Success",
                f"Saved {len(valid_features)} buildings to {os.path.basename(out_path)}",
                level=Qgis.Success
            )
        else:
            self.iface.messageBar().pushMessage(
                "Warning",
                "All buildings were filtered out. Check the Debug Candidates layer and loosen parameters.",
                level=Qgis.Warning
            )

    # =========================================================================
    # MAIN EXECUTION
    # =========================================================================
    def run_logic(self):
        # Re-entrancy guard — processEvents() inside the progress bar can fire
        # this slot again if the user double-clicks Run or Qt drains the queue.
        if self._running:
            return
        self._running = True
        try:
            self._run_logic_inner()
        finally:
            self._running = False

    def _run_logic_inner(self):
        # Check dependencies first
        if not self.check_dependencies():
            return
        
        # Now import
        import numpy as np
        from osgeo import gdal
        
        if not hasattr(self.dlg, 'mQgsFileWidget_laz'): 
            return
            
        laz_path = self.dlg.mQgsFileWidget_laz.filePath()
        
        # Validate input file
        if not laz_path or not os.path.exists(laz_path):
            QMessageBox.warning(
                self.iface.mainWindow(),
                "Invalid Input",
                "Please select a valid LAS/LAZ file."
            )
            return
        
        # Get absolute path for input
        laz_path = os.path.abspath(laz_path)
        
        # Determine output directory
        if hasattr(self.dlg, 'lineEdit_Output') and self.dlg.lineEdit_Output.text():
            out_dir = self.dlg.lineEdit_Output.text()
        else:
            out_dir = os.path.dirname(laz_path)
        
        # Convert to absolute path
        out_dir = os.path.abspath(out_dir)
        
        # Create output directory if it doesn't exist
        if not os.path.exists(out_dir):
            try:
                os.makedirs(out_dir)
            except Exception as e:
                QMessageBox.critical(
                    self.iface.mainWindow(),
                    "Directory Error",
                    f"Cannot create output directory:\n{out_dir}\n\nError: {str(e)}"
                )
                return
        
        # Check write permissions
        if not os.access(out_dir, os.W_OK):
            QMessageBox.critical(
                self.iface.mainWindow(),
                "Permission Error",
                f"No write permission for output directory:\n{out_dir}\n\n"
                f"Please select a different output folder or run QGIS as administrator."
            )
            return

        # ---- Read core parameters from dialog ----
        RESOLUTION    = float(self.dlg.get_param('resolution',  1.0))
        EPSG_CODE     = int(self.dlg.get_param('epsg_code',    0))
        ALPHA_VAL     = self.dlg.get_param('alpha',          0.7)
        MIN_SIZE     = self.dlg.get_param('min_size',       100)
        MAX_SIZE     = self.dlg.get_param('max_size',       50000)
        SQUARE_THRESH = self.dlg.get_param('squareness',    0.3)
        WIDTH_THRESH  = self.dlg.get_param('width',         3.0)
        KERNEL_SIZE   = self.dlg.get_param('kernel_size',   7)

        # ---- Read NEW false-positive filter params from dialog ----
        HEIGHT_VAR_THRESH      = self.dlg.get_param('height_var_thresh',      2.5)
        CONVEX_HULL_RATIO_MIN  = self.dlg.get_param('convex_hull_ratio_min',  0.5)
        MAX_ELONGATION         = self.dlg.get_param('max_elongation',         8.0)
        USE_PER_COMPONENT      = self.dlg.get_param('use_per_component',      True)
        SKIP_RASTERS           = self.dlg.get_param('skip_rasters',           False)

        try:
            dsm_path  = os.path.join(out_dir, "dsm.tif")
            dtm_path  = os.path.join(out_dir, "dtm.tif")
            ndhm_path = os.path.join(out_dir, "ndhmtemp.tif")

            # ---- Progress bar setup ----
            total_steps = 4 if SKIP_RASTERS else 7
            progress = QProgressDialog("Initialising…", "Cancel", 0, total_steps, self.iface.mainWindow())
            progress.setWindowTitle("LasBuildSeg")
            progress.setWindowModality(Qt.WindowModal)
            progress.setMinimumWidth(420)
            progress.setValue(0)
            progress.show()

            def step(n, label):
                progress.setValue(n)
                progress.setLabelText(label)
                # Force the GUI to repaint so the label actually updates
                from qgis.PyQt.QtWidgets import QApplication
                QApplication.processEvents()
                if progress.wasCanceled():
                    raise Exception("Processing cancelled by user.")

            if SKIP_RASTERS:
                missing = [p for p in [dsm_path, dtm_path, ndhm_path]
                           if not os.path.exists(p)]
                if missing:
                    progress.close()
                    QMessageBox.critical(
                        self.iface.mainWindow(),
                        "Missing Raster Files",
                        "Cannot skip raster generation — these files are missing:\n\n"
                        + "\n".join(f"  • {os.path.basename(p)}" for p in missing)
                        + "\n\nUncheck 'Skip DSM/DTM/nDHM generation' and run again."
                    )
                    return

                step(1, "Loading existing DSM / nDHM…")
                ds = gdal.Open(dsm_path)
                dsm_array = ds.GetRasterBand(1).ReadAsArray()
                gt        = ds.GetGeoTransform()
                proj_wkt  = ds.GetProjection()
                ds = None
                if not EPSG_CODE and proj_wkt:
                    try:
                        from osgeo import osr as _o; _s=_o.SpatialReference()
                        _s.ImportFromWkt(proj_wkt); _c=_s.GetAuthorityCode(None)
                        if _c and str(_c).isdigit(): EPSG_CODE=int(_c)
                    except Exception: pass

                ds = gdal.Open(ndhm_path)
                ndhm = ds.GetRasterBand(1).ReadAsArray().astype(np.float32)
                ds = None
                # Keep raw values from ndhmtemp.tif — same as standalone

            else:
                step(1, "Step 1/7 — Analysing LAZ file…")
                csf_params = self.laz_pre_analysis(laz_path)

                step(2, "Step 2/7 — Generating DSM (griddata nearest)…")
                auto_epsg = self.generate_dsm_pdal(laz_path, dsm_path, resolution=RESOLUTION)
                if not EPSG_CODE and auto_epsg: EPSG_CODE = auto_epsg

                step(3, "Step 3/7 — Generating DTM (CSF + griddata nearest)…")
                dtm_array, gt, proj_wkt = self.generate_dtm_csf_pdal(laz_path, dsm_path, csf_params)
                self.save_raster_qgis(dtm_array, dtm_path, gt, proj_wkt)

                step(4, "Step 4/7 — Computing nDHM (DSM − DTM, exact port of Lasb.generate_ndhm)…")
                # Read both from disk in same bottom-up orientation (positive Y step).
                # Both have same orientation so row-by-row subtraction is geographically correct.
                # NO alignment needed — DTM linspace grid ≈ DSM arange grid for nearest interp.
                # NO clipping — Lasb.generate_ndhm does raw ndhm = dsm - dtm with no manipulation.
                # Clipping to 0 was causing wrong statistics by diluting building heights + destroying gradients.
                ds = gdal.Open(dsm_path)
                dsm_array = ds.GetRasterBand(1).ReadAsArray().astype(np.float32); ds = None
                ndhm = dsm_array - dtm_array   # raw subtraction, exact port of Lasb.generate_ndhm
                self.save_raster_qgis(ndhm, ndhm_path, gt, proj_wkt)

            # Steps from here are the same whether rasters were skipped or not
            offset = 1 if SKIP_RASTERS else 4

            step(offset + 1, f"Step {offset+1}/{total_steps} — Analysing height distribution…")
            alphashape_h_thresh, filter_h_thresh, tri_thresh = self.analyze_low_res_ndhm(ndhm, ndhm_path=ndhm_path)

            step(offset + 2, f"Step {offset+2}/{total_steps} — Extracting building candidates…")
            out_json = os.path.join(out_dir, "buildings_filtered.geojson")

            self.extract_and_filter(
                ndhm, dsm_array, gt, proj_wkt,
                alpha=ALPHA_VAL,
                alphashape_h_thresh=alphashape_h_thresh,
                filter_h_thresh=filter_h_thresh,
                tri_thresh=tri_thresh,
                min_size=MIN_SIZE,
                max_size=MAX_SIZE,
                sq_thresh=SQUARE_THRESH,
                w_thresh=WIDTH_THRESH,
                kernel_size=KERNEL_SIZE,
                out_path=out_json,
                height_var_thresh=HEIGHT_VAR_THRESH,
                convex_hull_ratio_min=CONVEX_HULL_RATIO_MIN,
                max_elongation=MAX_ELONGATION,
                use_per_component=USE_PER_COMPONENT,
                epsg_code=EPSG_CODE,
            )

            step(total_steps, f"Done — output saved to {os.path.basename(out_dir)}")
            progress.close()

            self.iface.messageBar().pushMessage(
                "LasBuildSeg Complete",
                f"Done! Thresholds: AlphaShape={alphashape_h_thresh:.2f}m, Filter={filter_h_thresh:.2f}m. Output CRS: EPSG:3857",
                level=Qgis.Success,
                duration=10
            )

        except Exception as e:
            try:
                progress.close()
            except Exception:
                pass
            self.iface.messageBar().pushMessage("Error", f"{str(e)}", level=Qgis.Critical)
            import traceback
            traceback.print_exc()
            QgsMessageLog.logMessage(traceback.format_exc(), "LasBuildSeg", level=Qgis.Critical)